spring.application.name=AiPoweredTaskManagement

spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:15224/railway
spring.datasource.username=root
spring.datasource.password=UNaKEmzlkemiZgLFSAgydVSFVUxvLUmT

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true 

my.secret.key=ThisIsMySuperSecureJwtSecretKeyAndYodfggfkingofcobrafddsshghgyuyimm 
my.gemini.key=AQ.Ab8RN6IwcaBAn2Y9t2rarRKDSasbpkEvT4ZvOVvB0_X7FDLq3A
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
